RUN sudo chown -R ubuntu:ubuntu /home/ubuntu

# clean all apt packages installed
RUN sudo rm -rf /var/lib/apt/lists/*

# Enable apt-get completion after running `apt-get update` in the container
RUN sudo rm /etc/apt/apt.conf.d/docker-clean

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "sudo", "-E", "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]